language: node_js
node_js:
  - "8"
branches:
  only:
  - master

install:
  - npm install -g firebase-tools
  - npm install firebase-admin
 
script: 
  - npm run-script build
  - echo "Deploy!!"



after_success:
  - firebase deploy --project projectId --token "1/lJKKZPRSiEaxUC5M_-YFkUx_8B5SXpSQOmnGag1giPU"
