language: node_js
node_js:
  - "8"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - functions/node_modules
  
before_install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
install:
  - npm install firebase-admin
 
script: 
  
  - npm install
  - cd functions
  - npm install # install node module
  - cd ..
  - CI=false npm run build # build project
  - echo "Deploy!!"

after_success:
  - firebase deploy --project $PROJECT_ID" --non-interactive --token $FIREBASE_TOKEN