language: node_js
node_js:
  - "8"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
  - yarn lint
  - yarn build
after_success:
  - firebase deploy --project projectId --token "1/lJKKZPRSiEaxUC5M_-YFkUx_8B5SXpSQOmnGag1giPU"