language: node_js
node_js:
  - "8"
branches:
  only:
  - master
  - new
cache:
  directories:
  - node_modules
  - functions/node_modules
  
before_install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
install:
  - npm install firebase-admin
 
script: 
  - CI=false SKIP_PREFLIGHT_CHECK=true  npm run build # build project
  - echo "Deploy!!"

after_success:
  - firebase use --token ${FIREBASE_TOKEN} # set firebase token
  - firebase use --add ${PROJECT_ID} # set current project
  - firebase deploy --non-interactive --token "${FIREBASE_TOKEN}"