cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  11.4.0
   # use node version 11.4.0
branches:
  only: 
  - master # auto build and deploy in only master branch
script: # run after installed
- npm install # install node module
- npm run build # build project
install:
  npm install -g firebase-tools # install firebase-cli
after_success:
- firebase use --token ${1/F9bidVlz1FF5UfqWAGerdL8jWcNiXLIg6IysfMsATuk} # set firebase token
- firebase use --add ${deeplearning-7f788} # set current project
- firebase deploy --non-interactive --token "${FIREBASE_TOKEN}" # deploy project